---
eureka:
  client:
    serviceUrl:
      defaultZone: http://register:8010/eureka/
management:
  security:
    enabled: false
mongo:
  db:
    uri: mongodb://mongodb:27017/db
---
spring:
  profiles: register
---
spring:
  profiles: server_main